### ISSUE TITLE
'LaTeX Homework Template' blog page not rendering properly

### ISSUE THREAD

**Issue by dmackinnon1** [dcernst/dcernst.github.io#17]
Looking at the [page about your LaTeX homework template](http://danaernst.com/latex-homework-template/), near the bottom there seem to be some misplaced html tags that cause the formatting to go off. 

Also, the code sample included on the [markdown file](https://github.com/dcernst/dcernst.github.io/blob/master/_posts/2012-08-20-latex-homework-template.md) that generates the page is not showing.

The md page looks fine, so maybe some problem with Jekyll rendering the code caused the later formatting issues...

**Comment by dcernst** [comment]
Thanks for letting me know!  I'll work on fixing it now.

**Comment by dcernst** [comment]
Seems to be good now.  Thanks again.
